POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "test",
  "name": "Test User",
  "password": "test",
  "email": "myemail@email.com"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "root",
  "name": "Superuser",
  "password": "test",
  "email": "myemail@email.com"
}

###
GET http://localhost:3003/api/users/

###
DELETE http://localhost:3003/api/users/64ff96297079dd5a4d82316f