###
# Get all prototypes with success (not need token)
GET http://localhost:3003/api/prototypes

###
# Login with success to get token
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "root",
    "password": "test"
}

###
# Create a prototype with success (token provided)
POST http://localhost:3003/api/prototypes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0ZmY5NjUzNmU1NjFkOTg2MDkyYWY1ZiIsImlhdCI6MTY5NDQ3MjA2MX0.pcBkU-C2mopwEoBsqnsv6zl5bOLBCeJmfAZQ3_HHABw

{
  "title": "Fugas o la ansiedad de sentirse vivo",
  "userId": "64fed2923a2063db2c03bbc7"
}

###
# Update a prototype
PUT http://localhost:3003/api/prototypes/6501d942459e0f5f046fe9eb
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY1MDFkODliNDU5ZTBmNWYwNDZmZTlkNSIsImlhdCI6MTY5NDY1NDc2M30.9_3nKr1TmFvfLgJpJyJS2wbs2Mib-rjflNbAQSGH7tseyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0ZmY5NjUzNmU1NjFkOTg2MDkyYWY1ZiIsImlhdCI6MTY5NDYxMzU5Nn0.RQ8rtgOAET2zPP49M77XPXtm750wiaGFpC4raHbh2nQ

{
"title": "El nuevo ocaso 2"
}

###
# Update a prototype with token 
POST http://localhost:3003/api/prototypes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0ZmY5NjUzNmU1NjFkOTg2MDkyYWY1ZiIsImlhdCI6MTY5NDQ3MjA2MX0.pcBkU-C2mopwEoBsqnsv6zl5bOLBCeJmfAZQ3_HHABw

{
  "title": "El nuevo ocaso",
  "userId": "64fed2923a2063db2c03bbc7"
}

###
# Delete a prototype with success (token provided)
DELETE http://localhost:3003/api/prototypes/6501c28cafdaa3643dcd0633
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0ZmY5NjUzNmU1NjFkOTg2MDkyYWY1ZiIsImlhdCI6MTY5NDYxNDIxOX0.Euwz-1ZdOhVHGK52vaXQa_s0K9p5jslbm7OynqtNHN0


###
# Create a prototype withou token
POST http://localhost:3003/api/prototypes
Content-Type: application/json

{
  "title": "Test of blog title 2",
}

###
# Delete a prototype with error (not token provided)
DELETE http://localhost:3003/api/prototypes/6501c28cafdaa3643dcd0633

