###
# Get all books with success (not need token)
GET http://localhost:3003/api/books

###
# Login with success to get token
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "albe",
    "password": "test"
}

###
# Create a book with success (token provided)
POST http://localhost:3003/api/books
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsYmUiLCJpZCI6IjY1MDIyNmZmYzcyNDRiMzBmODcyZTFjZSIsImlhdCI6MTY5NDYzOTkxMH0.nizBayF_5XgRni0_3zOL6xs8qJAW6HUe2IUP4my66kM

{
  "title": "El resplandor",
        "pages": 688,
        "genre": "Terror",
        "cover": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1641398308i/60038757.jpg",
        "synopsis": "Una familia se muda a un hotel aislado para el invierno donde una presencia siniestra influye en el padre hacia la violencia.",
        "year": 1977,
        "ISBN": "978-0307743657",
        "author":  "Stephen King"
}

###
# Update a book
PUT http://localhost:3003/api/books/65024e950e6ac398dc7cded1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsYmUiLCJpZCI6IjY1MDIyNmZmYzcyNDRiMzBmODcyZTFjZSIsImlhdCI6MTY5NDYzOTkxMH0.nizBayF_5XgRni0_3zOL6xs8qJAW6HUe2IUP4my66kM

{
"title":   "El resplandor 2"  
}

###
# Update a book with token 
POST http://localhost:3003/api/books
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0ZmY5NjUzNmU1NjFkOTg2MDkyYWY1ZiIsImlhdCI6MTY5NDQ3MjA2MX0.pcBkU-C2mopwEoBsqnsv6zl5bOLBCeJmfAZQ3_HHABw

{
  "title": "El nuevo ocaso",
  "userId": "64fed2923a2063db2c03bbc7"
}

###
# Delete a book with success (token provided)
DELETE http://localhost:3003/api/books/65022abab1fb97088824b9f2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsYmUiLCJpZCI6IjY1MDIyNmZmYzcyNDRiMzBmODcyZTFjZSIsImlhdCI6MTY5NDYzOTkxMH0.nizBayF_5XgRni0_3zOL6xs8qJAW6HUe2IUP4my66kM


###
# Create a book withou token
POST http://localhost:3003/api/books
Content-Type: application/json

{
  "title": "Test of blog title 2",
}

###
# Delete a book with error (not token provided)
DELETE http://localhost:3003/api/books/6501c28cafdaa3643dcd0633

