###
# Get all users
GET http://localhost:3003/api/users/

###
# Create a new user
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "test",
  "name": "Test User",
  "password": "test",
  "email": "myemail@email.com"
}

###
# Create a new user
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "albe",
  "name": "albe",
  "password": "test",
  "email": "myemail@email.com"
}

###
# Create a new user
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "root",
  "name": "Superuser",
  "password": "test",
  "email": "myemail@email.com"
}

###
# Update a user
PUT http://localhost:3003/api/users/64ff96536e561d986092af5f
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0ZmY5NjUzNmU1NjFkOTg2MDkyYWY1ZiIsImlhdCI6MTY5NDYxMzU5Nn0.RQ8rtgOAET2zPP49M77XPXtm750wiaGFpC4raHbh2nQ

{
  "username": "root",
  "name": "Superuser",
  "password": "test123",
  "email": "myemail@email.com"
}

###
DELETE http://localhost:3003/api/users/64ff96297079dd5a4d82316f